import {
  FaAngular,
  FaCss3Alt,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaJava,
  FaLess,
  FaNodeJs,
  FaPhp,
  FaProjectDiagram,
  FaPython,
  FaReact,
  FaSass,
  FaUsers,
  FaVuejs,
} from "react-icons/fa";
import {
  SiAmazon,
  SiBootstrap,
  SiCplusplus,
  SiCypress,
  SiDjango,
  SiDotnet,
  SiExpress,
  SiFirebase,
  SiFlask,
  SiGo,
  SiGraphql,
  SiHeroku,
  SiJavascript,
  SiJest,
  SiJira,
  SiKubernetes,
  SiLaravel,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiPostgresql,
  SiPrisma,
  SiRedis,
  SiRedux,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiSharp,
  SiSpring,
  SiStyledcomponents,
  SiSvelte,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWordpress,
} from "react-icons/si";

export const availableIcons = {
  FaHtml5: <FaHtml5 />,
  FaCss3Alt: <FaCss3Alt />,
  SiJavascript: <SiJavascript />,
  SiTypescript: <SiTypescript />,
  FaReact: <FaReact />,
  FaAngular: <FaAngular />,
  FaVuejs: <FaVuejs />,
  SiSvelte: <SiSvelte />,
  SiNextdotjs: <SiNextdotjs />,
  SiRedux: <SiRedux />,
  SiTailwindcss: <SiTailwindcss />,
  SiBootstrap: <SiBootstrap />,
  SiStyledcomponents: <SiStyledcomponents />,
  SiMui: <SiMui />,
  FaSass: <FaSass />,
  FaLess: <FaLess />,
  FaNodeJs: <FaNodeJs />,
  SiExpress: <SiExpress />,
  FaPython: <FaPython />,
  SiDjango: <SiDjango />,
  SiFlask: <SiFlask />,
  FaPhp: <FaPhp />,
  FaJava: <FaJava />,
  SiSpring: <SiSpring />,
  SiGo: <SiGo />,
  SiRust: <SiRust />,
  SiSharp: <SiSharp />,
  SiDotnet: <SiDotnet />,
  SiCplusplus: <SiCplusplus />,
  SiLaravel: <SiLaravel />,
  SiRuby: <SiRuby />,
  SiRubyonrails: <SiRubyonrails />,
  SiPostgresql: <SiPostgresql />,
  SiMongodb: <SiMongodb />,
  SiMysql: <SiMysql />,
  SiGraphql: <SiGraphql />,
  SiPrisma: <SiPrisma />,
  SiFirebase: <SiFirebase />,
  SiRedis: <SiRedis />,
  FaGitAlt: <FaGitAlt />,
  FaDocker: <FaDocker />,
  SiKubernetes: <SiKubernetes />,
  SiVite: <SiVite />,
  SiJest: <SiJest />,
  SiCypress: <SiCypress />,
  SiAmazon: <SiAmazon />,
  SiHeroku: <SiHeroku />,
  SiNetlify: <SiNetlify />,
  SiVercel: <SiVercel />,
  SiWordpress: <SiWordpress />,
  FaProjectDiagram: <FaProjectDiagram />,
  SiJira: <SiJira />,
  FaUsers: <FaUsers />,
};

export const iconNameMap: { [key: string]: string } = Object.keys(
  availableIcons
).reduce((acc, key) => {
  const name = key.replace(/^(Fa|Si)/, "");
  acc[name] = key;
  return acc;
}, {} as { [key: string]: string });
